// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

/**
 * @title RiskOracle
 * @notice Stores the latest ML-generated crop risk score per district, submitted and signed by
 *         an authorized off-chain oracle relayer. Each score is a uint8 in the range 0–100.
 *
 * @dev The oracle relayer (e.g., a Node.js service running the ML pipeline) signs the tuple
 *      (districtId, riskScore, timestamp) with its private key, then calls submitRiskScore.
 *      On-chain ECDSA verification ensures no unauthorized party can fake a score update.
 *
 *      Replay protection: timestamps must be strictly increasing per district, so an attacker
 *      cannot replay an old signed message to reset the score.
 *
 *      Freshness protection: timestamps cannot be more than 1 hour in the future, preventing
 *      pre-dated score injections.
 */
contract RiskOracle {
    using ECDSA for bytes32;

    /// @notice The only authorized signer (oracle relayer address) set at deployment.
    address public immutable ORACLE_ADDRESS;

    /// @dev Holds the latest score and its timestamp for each district.
    struct DistrictScore {
        uint8  riskScore;    // 0–100
        uint256 timestamp;   // Unix epoch when the score was submitted
    }

    /// @notice districtId => latest DistrictScore
    mapping(uint256 => DistrictScore) private _scores;

    /// @notice Emitted on every accepted score update from the oracle relayer.
    event RiskScoreUpdated(
        uint256 indexed districtId,
        uint8           riskScore,
        uint256         timestamp
    );

    /**
     * @param oracleAddress The address of the authorized off-chain oracle relayer.
     *        This is the account that signs (districtId, riskScore, timestamp) payloads.
     */
    constructor(address oracleAddress) {
        require(oracleAddress != address(0), "RiskOracle: zero oracle address");
        ORACLE_ADDRESS = oracleAddress;
    }

    /**
     * @notice Submit a signed risk score update for a district.
     * @param districtId  Unique district identifier (matches the ML pipeline district key).
     * @param riskScore   Risk score 0–100 generated by the off-chain ML model.
     * @param timestamp   Unix timestamp at which the score was generated (must be strictly
     *                    greater than the last accepted timestamp for this district and no
     *                    more than 1 hour ahead of block.timestamp).
     * @param signature   ECDSA signature of keccak256(abi.encodePacked(districtId, riskScore,
     *                    timestamp)) produced by ORACLE_ADDRESS.
     */
    function submitRiskScore(
        uint256 districtId,
        uint8   riskScore,
        uint256 timestamp,
        bytes calldata signature
    ) external {
        require(riskScore <= 100, "RiskOracle: score out of range");
        require(
            timestamp > _scores[districtId].timestamp,
            "RiskOracle: timestamp not strictly increasing (replay protection)"
        );
        require(
            timestamp <= block.timestamp + 1 hours,
            "RiskOracle: timestamp too far in the future (freshness check)"
        );

        // --- Signature Verification ---
        // Build the same message hash the relayer signed.
        bytes32 msgHash = keccak256(abi.encodePacked(districtId, riskScore, timestamp));
        // Wrap with the Ethereum Signed Message prefix (EIP-191) to match eth_sign / signMessage.
        bytes32 ethMsgHash = MessageHashUtils.toEthSignedMessageHash(msgHash);
        // Recover the signer and verify it matches the authorized oracle.
        address recovered = ethMsgHash.recover(signature);
        require(recovered == ORACLE_ADDRESS, "RiskOracle: invalid signature (bad signer)");

        _scores[districtId] = DistrictScore({ riskScore: riskScore, timestamp: timestamp });

        emit RiskScoreUpdated(districtId, riskScore, timestamp);
    }

    /**
     * @notice Returns the latest risk score and its timestamp for a district.
     * @param districtId  Unique district identifier.
     * @return riskScore  Latest risk score (0–100). Returns 0 if no score has been submitted.
     * @return timestamp  Unix timestamp of the latest submitted score. Returns 0 if never set.
     */
    function getLatestScore(uint256 districtId)
        external
        view
        returns (uint8 riskScore, uint256 timestamp)
    {
        DistrictScore storage s = _scores[districtId];
        return (s.riskScore, s.timestamp);
    }
}
